// Generated by CoffeeScript 1.3.3

$(function() {
  var canvasElm, context, height, imageData, imageElm, width, worker;
  worker = new Worker("js/worker.js");
  canvasElm = $("#canvas");
  context = canvasElm.get(0).getContext('2d');
  width = canvasElm.width();
  height = canvasElm.height();
  imageElm = $(".item>img");
  imageData = null;
  imageElm.load(function() {
    context.drawImage(imageElm.get(0), 0, 0);
    imageData = context.getImageData(0, 0, width, height);
    return $("#loading").fadeOut();
  });
  $("#apply").click(function() {
    var inputs, matrix, x, y, _i, _j;
    $("#loading").fadeIn();
    inputs = $("form input");
    matrix = [[], [], []];
    for (x = _i = 0; _i <= 2; x = ++_i) {
      for (y = _j = 0; _j <= 2; y = ++_j) {
        matrix[x][y] = parseFloat(inputs.eq(x * 3 + y).val());
      }
    }
    return worker.postMessage({
      imageData: imageData,
      filterData: context.createImageData(width, height),
      matrix: matrix
    });
  });
  worker.onmessage = function(event) {
    context.putImageData(event.data, 0, 0);
    return $("#loading").fadeOut();
  };
  return true;
});
